version: "3"

services:
  nexus:
    image: sczuka/sonatype-nexus3-github-oauth:version-3.16.1.1
    volumes:
      - nexus-data:/nexus-data
      - "./githuboauth.properties:/opt/sonatype/nexus/etc/githuboauth.properties:ro"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./server.crt:/etc/ssl/certs/server.crt:ro"
      - "./server.key:/etc/ssl/certs/server.key:ro"
    ports:
      - 443:443
      - 9080:9080
      - 9081:9081
    restart: unless-stopped

volumes:
  nexus-data: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/nexus3/data'
